version: '3'
services:
  wordpress:
    image: visiblevc/wordpress:latest
    ports:
      - 8080:80
      - 443:443
    restart: always
    volumes:
      - ./data:/data # Required if importing an existing database
      - ./tweaks.ini:/usr/local/etc/php/conf.d/tweaks.ini # Optional tweaks to the php.ini config
      - ./uploads:/app/wp-content/uploads
      - ./plugins/simple-multi-cpts:/app/wp-content/plugins/simple-multi-cpts
      - ./themes/test:/app/wp-content/themes/test
      - ./themes/styleguide-wp-theme:/app/wp-content/themes/styleguide-wp-theme
    environment:
      DB_NAME: wordpress
      DB_PASS: ${SECURE_PASSWORD} # Stored in .env file
      PLUGINS: >-
        [local]simple-multi-cpts,
        [Basic-Auth]https://github.com/WP-API/Basic-Auth/archive/master.zip,
        [advanced-custom-fields-pro]http://connect.advancedcustomfields.com/index.php?p=pro&a=download&k=b3JkZXJfaWQ9MzU0MTJ8dHlwZT1kZXZlbG9wZXJ8ZGF0ZT0yMDE0LTA3LTIxIDIyOjI5OjEy,
        limit-login-attempts,
        wp-super-cache,
        duplicate-post,
        intuitive-custom-post-order,
        timber-library,
        password-protected,
        enhanced-media-library,
        regenerate-thumbnails,
        manual-image-crop,
        theme-my-login,
        wp-crontrol,
        query-monitor,
        debug-bar
      THEMES: >-
        [local]test,
        [local]styleguide-wp-theme
      SEARCH_REPLACE: yoursite.com,localhost:8080
      WP_DEBUG: 'true'
  db:
    restart: always
    image: mariadb:10 # or mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${SECURE_PASSWORD} # Stored in .env file
volumes:
  data:
